- name: Demonstrates installing JDK, Maven, git-clone, building application jar and creating a windows service
  hosts: all
  become_method: runas
  vars:
  - ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38353536643231323233376261333836653035323035643366326437396338643665323634613963
          6336353433323561393063663261613564626231656636620a653663656566323735643833383464
          64386562306537313462636233343566663639356265373333643863373563633133356136373866
          3333316630626634610a353230313534646361353266396639663666323534633536393166366436
          6632
  tasks:
  - name: Download the OpenJDK 20 zip file 
    win_get_url:
      url:  https://download.java.net/java/GA/jdk20.0.2/6e380f22cbe7469fa75fb448bd903d8e/9/GPL/openjdk-20.0.2_windows-x64_bin.zip
      dest: C:\openjdk20.zip

  - name: Unzip the OpenJDK 20
    win_unzip:
      src: C:\openjdk20.zip
      dest: C:\openjdk20

  - name: Add JDK_HOME environment variable for OpenJDK 20
    ansible.windows.win_environment:
      state: present
      name: JDK_HOME 
      value: C:\openjdk20\jdk-20.0.2 
      level: machine

  - name: Add JDK_HOME into system path 
    ansible.windows.win_path:
      elements:
        - '%JDK_HOME%\bin'
      scope: machine 
      state: present

  - name: Download the Maven 3.9.4 zip file
    win_get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip 
      dest: C:\maven.zip

  - name: Unzip Maven 3.9.4
    win_unzip:
      src: C:\maven.zip
      dest: C:\maven

  - name: Add M2_HOME environment variable into system environment
    ansible.windows.win_environment:
      state: present
      name: M2_HOME
      value: C:\maven\apache-maven-3.9.4
      level: machine

  - name: Add M2_HOME bin into system path 
    ansible.windows.win_path:
      elements:
        - '%M2_HOME%\bin'
      scope: machine 
      state: present

  - name: Reboot windows ansible node before using maven
    win_shell: powershell.exe Restart-Computer -ComputerName localhost -Force
    async: 5 
    poll: 0
    become: yes
    become_user: Administrator

  - name: Wait for the machine to come back online
    wait_for_connection:
      connect_timeout: 60
      sleep: 5
      delay: 5 
      timeout: 600

  - name: Clone TekTutor spring-boot sample application
    win_shell: git clone https://github.com/tektutor/spring-ms C:\Users\Administrator\spring-ms

  - name: Build the maven project
    win_shell:
       chdir: C:\Users\Administrator\spring-ms
       mvn clean package 

  - name: Create HelloMicroservice service for our custom spring-boot java application
    ansible.windows.win_service:
      name: HelloMicroservice
      path: C:\openjdk20\jdk-20.0.2\bin\java.exe -Xmx256m -jar C:\Users\Administrator\spring-ms\target\spring-hello-1.0.jar
      display_name: "Hello Microservice" 
      description: TekTutor SpringBoot Sample Microservice app 
    become: yes
    become_user: Administrator

  - name: Set service startup mode to auto and ensure it is started
    ansible.windows.win_service:
      name: "HelloMicroservice" 
      start_mode: auto
      state: started
    become: yes
    become_user: Administrator
