- name: Demonstrates installing JDK, Maven, git-clone, building application jar and creating a windows service
  hosts: all
  become_method: runas
  vars:
  - ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38353536643231323233376261333836653035323035643366326437396338643665323634613963
          6336353433323561393063663261613564626231656636620a653663656566323735643833383464
          64386562306537313462636233343566663639356265373333643863373563633133356136373866
          3333316630626634610a353230313534646361353266396639663666323534633536393166366436
          6632
  tasks:

  - name: Install winget windows package manager
    win_shell: | 
      $progressPreference = 'silentlyContinue'
      Write-Information "Downloading WinGet and its dependencies..."
      Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
      Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx -OutFile Microsoft.UI.Xaml.2.7.x64.appx
      Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
      Add-AppxPackage Microsoft.UI.Xaml.2.7.x64.appx
      Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

    become: yes
    become_user: Administrator

  - name: Install OpenJDK 17
    win_shell: powershell.exe winget install Microsoft.OpenJDK.17
    become: yes
    become_user: Administrator
