- name: This playbook demonstrates creating a custom registry entry 
  hosts: all 
  tasks:
   - name: Creating a registry
     win_regedit:
       path: HKLM:\SOFTWARE\TekTutor

   - name: Modifying a registry, adding name and data
     win_regedit:
      path: HKLM:\SOFTWARE\GeekFlare
      name: Training 
      data: Advanced Ansible - 5 Days 
