- name: This playbook demonstrates rebooting windows ansible node
  hosts: all
  become_method: runas
  vars:
  - ansible_become_password: rps@12345
  tasks:
  - name: Reboot windows ansible node
    win_shell: powershell.exe Restart-Computer -ComputerName localhost -Force
    async: 5 
    poll: 0
    become: yes
    become_user: Administrator

  - name: Wait for the machine to come back online
    wait_for_connection:
      connect_timeout: 60
      sleep: 5
      delay: 5 
      timeout: 600
