- name: This playbook will install nginx, configures custom path of web root folder and deploys custom web page
  hosts: all
  vars:
    - greeting_msg: "Welcome to DevOps!" 
    - conf_mgt_tool: Ansible
    - provisioner_tool: Docker
  tasks:
  - name: Install nginx in Ubuntu node
    apt: 
      name: nginx 
      state: latest 
      update_cache: yes

  - name: Start nginx web server in Ubuntu nodes
    shell: service nginx start

  - name: Create the custom web root folder
    file: path=/var/html state=directory mode=0755

  - name: Deploy custom html page
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Configure nginx web server to use our custom folder to pick the html pages
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx web server to apply config changes
    shell: service nginx restart
