- name: This playbook creates containers 
  hosts: localhost
  tasks:
    #  - name: Delete all running containers
    # shell: docker rm -f $(docker ps -aqf "name=ubuntu*|centos*")
    #ignore_errors: yes

  - name: Provision ubuntu containers
    docker_container:
      docker_host: tcp://localhost:4243
      name: "ubuntu-00{{item}}"
      hostname: "ubuntu-00{{item}}"
      image: "tektutor/ansible-ubuntu-node:latest"
      state: started 
      ports:
        - "8{{item}}:80"
        - "2{{item}}:22"
    with_sequence: start=1 end=10 format="%03d"

  - name: Provision centos containers
    docker_container:
      docker_host: tcp://localhost:4243
      name: "centos-00{{item}}"
      hostname: "centos-00{{item}}"
      image: "tektutor/ansible-centos-node:latest"
      state: started 
      ports:
        - "9{{item}}:80"
        - "3{{item}}:22"
    with_sequence: start=1 end=10 format="%03d"
